getting boot node ip fault tolerant
radixdlt/mtps pull request #42
Opened 2019-06-19 11:20 UTC by x-wf

2019-06-19 11:41 UTC, x-wf commented
#30

2019-06-20 08:08 UTC, blenessy requested changes

2019-06-20 08:08 UTC, blenessy commented on tools/libcloud/gcp.py
> +            while(not node.public_ips):
nope, you need to refresh the `node` metadata or you'll be stuck in this while loop forever:

```python
while not node.public_ips:
    logging.info("Waiting for %s to get its public IP ...", node.name)
    time.sleep(5)
    node = gce.ex_get_node(node.name)
 ```

2019-06-20 11:39 UTC, swiec requested changes
Oops, looks like you're fixing wrong line, take a look at logs attached to issue
` File "libcloud/mtps.py", line 166, in <module>
    os.environ["RADIX_MTPS_NETWORK_SEEDS"] = boot_node.public_ips[0]`
problem is in the line 166

2019-06-26 07:59 UTC, blenessy commented
superseded by #68

2019-06-26 07:59 UTC, closed without merging